name: build action
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - name: Build
        id: build
        uses: SkySoft-ATM/go-build-action@v1
        with:
          github_user:  ${{ secrets.BOT_USER }}
          github_token:  ${{ secrets.BOT_TOKEN }}
          gcloud_token:  ${{ secrets.GCLOUD_TOKEN }}
