name: golangci-lint_bin
on: [ push ]
jobs:
  cov_badge:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Set up Go 1.20
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
      - run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - run: golangci-lint run